import {
  AlertTriangle,
  CheckCircle2,
  Info,
  ShieldAlert,
} from "lucide-react";

const alerts = [
  {
    id: 1,
    type: "Critical",
    title: "High Dust Concentration",
    description: "Dust level exceeded the safety threshold in Zone A.",
    time: "2 min ago",
    color: "border-red-500",
    icon: <ShieldAlert className="text-red-500" size={24} />,
  },
  {
    id: 2,
    type: "Warning",
    title: "Battery Low",
    description: "Rover 03 battery dropped below 20%.",
    time: "8 min ago",
    color: "border-yellow-500",
    icon: <AlertTriangle className="text-yellow-400" size={24} />,
  },
  {
    id: 3,
    type: "Success",
    title: "Mission Completed",
    description: "Pipeline inspection finished successfully.",
    time: "18 min ago",
    color: "border-green-500",
    icon: <CheckCircle2 className="text-green-400" size={24} />,
  },
  {
    id: 4,
    type: "Information",
    title: "System Update",
    description: "AI navigation model updated successfully.",
    time: "35 min ago",
    color: "border-blue-500",
    icon: <Info className="text-blue-400" size={24} />,
  },
];

const Alerts = () => {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-white">
          AI Alerts
        </h1>

        <p className="mt-2 text-slate-400">
          Real-time notifications generated by the DustNet AI monitoring
          system.
        </p>
      </div>

      <div className="space-y-5">
        {alerts.map((alert) => (
          <div
            key={alert.id}
            className={`rounded-2xl border-l-4 ${alert.color} border border-slate-800 bg-slate-900 p-6`}
          >
            <div className="flex items-start justify-between">
              <div className="flex gap-4">
                <div>{alert.icon}</div>

                <div>
                  <h2 className="text-lg font-semibold text-white">
                    {alert.title}
                  </h2>

                  <p className="mt-2 text-slate-400">
                    {alert.description}
                  </p>

                  <span className="mt-4 inline-block rounded-lg bg-slate-800 px-3 py-1 text-xs text-orange-400">
                    {alert.type}
                  </span>
                </div>
              </div>

              <span className="text-sm text-slate-500">
                {alert.time}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Alerts;